[workspace]
resolver = "2"
members = [
    "./crates/*",
    "./apps/native/src-tauri",
]

[workspace.dependencies]
# Private
# specta-typescript = { version = "0.0.9", default-features = false }
# pin-project-lite = { version = "0.2", default-features = false }
# erased-serde = { version = "0.4", default-features = false }

# Public
# specta = { version = "=2.0.0-rc.22", default-features = false }
# serde = { version = "1", default-features = false }
# serde_json = { version = "1", default-features = false }
# futures = { version = "0.3", default-features = false }
# futures-core = { version = "0.3", default-features = false }
# futures-util = { version = "0.3", default-features = false }
# tracing = { version = "0.1", default-features = false }

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
unwrap_used = { level = "warn", priority = -1 }
panic = { level = "warn", priority = -1 }
todo = { level = "warn", priority = -1 }
panic_in_result_fn = { level = "warn", priority = -1 }
