services:
  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"  # MQTT
      - "9001:9001"  # WebSocket
    volumes:
      - ./.data/mosquitto/config:/mosquitto/config
      - ./.data/mosquitto/data:/mosquitto/data
      - ./.data/mosquitto/log:/mosquitto/log
    networks:
      - cove-network

  questdb:
    image: questdb/questdb:latest
    container_name: cove-questdb
    ports:
      - "9000:9000"  # HTTP API and web console
      - "9009:9009"  # InfluxDB line protocol
      - "8812:8812"  # PostgreSQL wire protocol (optional)
    volumes:
      - ./.data/questdb:/root/.questdb/db
    environment:
      - QDB_TELEMETRY_ENABLED=false  # Disable telemetry
    restart: unless-stopped
    networks:
      - cove-network
  esphome:
    image: esphome/esphome:latest
    container_name: cove-esphome
    ports:
      - "6053:6053"
    volumes:
      - ./.data/esphome/config:/config
    networks:
      - cove-network

networks:
  cove-network:
    name: cove-network