# yaml-language-server: $schema=./schemas/cove.schema.json

system:
  name: "Cove Home Automation"
  version: "0.1.0"

logging:
  level: INFO

discovery:
  protocols:
    - wifi:
        enabled: true
        discovery_timeout: 10
        discovery_interval: 10
        discovery_retries: 3
        discovery_retry_delay: 1
    - bluetooth:
        enabled: true
        discovery_timeout: 5
        discovery_interval: 30
        discovery_retries: 2
        discovery_retry_delay: 1
    - zigbee:
        enabled: false
        discovery_timeout: 5
        discovery_interval: 30
        discovery_retries: 2
        discovery_retry_delay: 1
    - matter:
        enabled: false
        discovery_timeout: 5
        discovery_interval: 30
        discovery_retries: 2
        discovery_retry_delay: 1
