// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=none"
// @generated from file api.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from '@bufbuild/protobuf';
import { void$ } from './api_options_pb';
import {
  AlarmControlPanelCommandRequest,
  AuthenticationRequest,
  AuthenticationResponse,
  BluetoothConnectionsFreeResponse,
  BluetoothDeviceRequest,
  BluetoothGATTGetServicesRequest,
  BluetoothGATTNotifyRequest,
  BluetoothGATTReadDescriptorRequest,
  BluetoothGATTReadRequest,
  BluetoothGATTWriteDescriptorRequest,
  BluetoothGATTWriteRequest,
  BluetoothScannerSetModeRequest,
  ButtonCommandRequest,
  CameraImageRequest,
  ClimateCommandRequest,
  CoverCommandRequest,
  DateCommandRequest,
  DateTimeCommandRequest,
  DeviceInfoRequest,
  DeviceInfoResponse,
  DisconnectRequest,
  DisconnectResponse,
  ExecuteServiceRequest,
  FanCommandRequest,
  HelloRequest,
  HelloResponse,
  LightCommandRequest,
  ListEntitiesRequest,
  LockCommandRequest,
  MediaPlayerCommandRequest,
  NoiseEncryptionSetKeyRequest,
  NoiseEncryptionSetKeyResponse,
  NumberCommandRequest,
  PingRequest,
  PingResponse,
  SelectCommandRequest,
  SirenCommandRequest,
  SubscribeBluetoothConnectionsFreeRequest,
  SubscribeBluetoothLEAdvertisementsRequest,
  SubscribeHomeAssistantStatesRequest,
  SubscribeHomeassistantServicesRequest,
  SubscribeLogsRequest,
  SubscribeStatesRequest,
  SubscribeVoiceAssistantRequest,
  SwitchCommandRequest,
  TextCommandRequest,
  TimeCommandRequest,
  UnsubscribeBluetoothLEAdvertisementsRequest,
  UpdateCommandRequest,
  ValveCommandRequest,
  VoiceAssistantConfigurationRequest,
  VoiceAssistantConfigurationResponse,
  VoiceAssistantSetConfiguration,
  ZWaveProxyFrame,
  ZWaveProxyRequest,
} from './api_pb';

/**
 * @generated from service APIConnection
 */
export const APIConnection = {
  methods: {
    /**
     * @generated from rpc APIConnection.alarm_control_panel_command
     */
    alarm_control_panel_command: {
      I: AlarmControlPanelCommandRequest,
      kind: MethodKind.Unary,
      name: 'alarm_control_panel_command',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.authenticate
     */
    authenticate: {
      I: AuthenticationRequest,
      kind: MethodKind.Unary,
      name: 'authenticate',
      O: AuthenticationResponse,
    },
    /**
     * @generated from rpc APIConnection.bluetooth_device_request
     */
    bluetooth_device_request: {
      I: BluetoothDeviceRequest,
      kind: MethodKind.Unary,
      name: 'bluetooth_device_request',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.bluetooth_gatt_get_services
     */
    bluetooth_gatt_get_services: {
      I: BluetoothGATTGetServicesRequest,
      kind: MethodKind.Unary,
      name: 'bluetooth_gatt_get_services',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.bluetooth_gatt_notify
     */
    bluetooth_gatt_notify: {
      I: BluetoothGATTNotifyRequest,
      kind: MethodKind.Unary,
      name: 'bluetooth_gatt_notify',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.bluetooth_gatt_read
     */
    bluetooth_gatt_read: {
      I: BluetoothGATTReadRequest,
      kind: MethodKind.Unary,
      name: 'bluetooth_gatt_read',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.bluetooth_gatt_read_descriptor
     */
    bluetooth_gatt_read_descriptor: {
      I: BluetoothGATTReadDescriptorRequest,
      kind: MethodKind.Unary,
      name: 'bluetooth_gatt_read_descriptor',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.bluetooth_gatt_write
     */
    bluetooth_gatt_write: {
      I: BluetoothGATTWriteRequest,
      kind: MethodKind.Unary,
      name: 'bluetooth_gatt_write',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.bluetooth_gatt_write_descriptor
     */
    bluetooth_gatt_write_descriptor: {
      I: BluetoothGATTWriteDescriptorRequest,
      kind: MethodKind.Unary,
      name: 'bluetooth_gatt_write_descriptor',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.bluetooth_scanner_set_mode
     */
    bluetooth_scanner_set_mode: {
      I: BluetoothScannerSetModeRequest,
      kind: MethodKind.Unary,
      name: 'bluetooth_scanner_set_mode',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.button_command
     */
    button_command: {
      I: ButtonCommandRequest,
      kind: MethodKind.Unary,
      name: 'button_command',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.camera_image
     */
    camera_image: {
      I: CameraImageRequest,
      kind: MethodKind.Unary,
      name: 'camera_image',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.climate_command
     */
    climate_command: {
      I: ClimateCommandRequest,
      kind: MethodKind.Unary,
      name: 'climate_command',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.cover_command
     */
    cover_command: {
      I: CoverCommandRequest,
      kind: MethodKind.Unary,
      name: 'cover_command',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.date_command
     */
    date_command: {
      I: DateCommandRequest,
      kind: MethodKind.Unary,
      name: 'date_command',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.datetime_command
     */
    datetime_command: {
      I: DateTimeCommandRequest,
      kind: MethodKind.Unary,
      name: 'datetime_command',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.device_info
     */
    device_info: {
      I: DeviceInfoRequest,
      kind: MethodKind.Unary,
      name: 'device_info',
      O: DeviceInfoResponse,
    },
    /**
     * @generated from rpc APIConnection.disconnect
     */
    disconnect: {
      I: DisconnectRequest,
      kind: MethodKind.Unary,
      name: 'disconnect',
      O: DisconnectResponse,
    },
    /**
     * @generated from rpc APIConnection.execute_service
     */
    execute_service: {
      I: ExecuteServiceRequest,
      kind: MethodKind.Unary,
      name: 'execute_service',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.fan_command
     */
    fan_command: {
      I: FanCommandRequest,
      kind: MethodKind.Unary,
      name: 'fan_command',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.hello
     */
    hello: {
      I: HelloRequest,
      kind: MethodKind.Unary,
      name: 'hello',
      O: HelloResponse,
    },
    /**
     * @generated from rpc APIConnection.light_command
     */
    light_command: {
      I: LightCommandRequest,
      kind: MethodKind.Unary,
      name: 'light_command',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.list_entities
     */
    list_entities: {
      I: ListEntitiesRequest,
      kind: MethodKind.Unary,
      name: 'list_entities',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.lock_command
     */
    lock_command: {
      I: LockCommandRequest,
      kind: MethodKind.Unary,
      name: 'lock_command',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.media_player_command
     */
    media_player_command: {
      I: MediaPlayerCommandRequest,
      kind: MethodKind.Unary,
      name: 'media_player_command',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.noise_encryption_set_key
     */
    noise_encryption_set_key: {
      I: NoiseEncryptionSetKeyRequest,
      kind: MethodKind.Unary,
      name: 'noise_encryption_set_key',
      O: NoiseEncryptionSetKeyResponse,
    },
    /**
     * @generated from rpc APIConnection.number_command
     */
    number_command: {
      I: NumberCommandRequest,
      kind: MethodKind.Unary,
      name: 'number_command',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.ping
     */
    ping: {
      I: PingRequest,
      kind: MethodKind.Unary,
      name: 'ping',
      O: PingResponse,
    },
    /**
     * @generated from rpc APIConnection.select_command
     */
    select_command: {
      I: SelectCommandRequest,
      kind: MethodKind.Unary,
      name: 'select_command',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.siren_command
     */
    siren_command: {
      I: SirenCommandRequest,
      kind: MethodKind.Unary,
      name: 'siren_command',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.subscribe_bluetooth_connections_free
     */
    subscribe_bluetooth_connections_free: {
      I: SubscribeBluetoothConnectionsFreeRequest,
      kind: MethodKind.Unary,
      name: 'subscribe_bluetooth_connections_free',
      O: BluetoothConnectionsFreeResponse,
    },
    /**
     * @generated from rpc APIConnection.subscribe_bluetooth_le_advertisements
     */
    subscribe_bluetooth_le_advertisements: {
      I: SubscribeBluetoothLEAdvertisementsRequest,
      kind: MethodKind.Unary,
      name: 'subscribe_bluetooth_le_advertisements',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.subscribe_home_assistant_states
     */
    subscribe_home_assistant_states: {
      I: SubscribeHomeAssistantStatesRequest,
      kind: MethodKind.Unary,
      name: 'subscribe_home_assistant_states',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.subscribe_homeassistant_services
     */
    subscribe_homeassistant_services: {
      I: SubscribeHomeassistantServicesRequest,
      kind: MethodKind.Unary,
      name: 'subscribe_homeassistant_services',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.subscribe_logs
     */
    subscribe_logs: {
      I: SubscribeLogsRequest,
      kind: MethodKind.Unary,
      name: 'subscribe_logs',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.subscribe_states
     */
    subscribe_states: {
      I: SubscribeStatesRequest,
      kind: MethodKind.Unary,
      name: 'subscribe_states',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.subscribe_voice_assistant
     */
    subscribe_voice_assistant: {
      I: SubscribeVoiceAssistantRequest,
      kind: MethodKind.Unary,
      name: 'subscribe_voice_assistant',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.switch_command
     */
    switch_command: {
      I: SwitchCommandRequest,
      kind: MethodKind.Unary,
      name: 'switch_command',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.text_command
     */
    text_command: {
      I: TextCommandRequest,
      kind: MethodKind.Unary,
      name: 'text_command',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.time_command
     */
    time_command: {
      I: TimeCommandRequest,
      kind: MethodKind.Unary,
      name: 'time_command',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.unsubscribe_bluetooth_le_advertisements
     */
    unsubscribe_bluetooth_le_advertisements: {
      I: UnsubscribeBluetoothLEAdvertisementsRequest,
      kind: MethodKind.Unary,
      name: 'unsubscribe_bluetooth_le_advertisements',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.update_command
     */
    update_command: {
      I: UpdateCommandRequest,
      kind: MethodKind.Unary,
      name: 'update_command',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.valve_command
     */
    valve_command: {
      I: ValveCommandRequest,
      kind: MethodKind.Unary,
      name: 'valve_command',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.voice_assistant_get_configuration
     */
    voice_assistant_get_configuration: {
      I: VoiceAssistantConfigurationRequest,
      kind: MethodKind.Unary,
      name: 'voice_assistant_get_configuration',
      O: VoiceAssistantConfigurationResponse,
    },
    /**
     * @generated from rpc APIConnection.voice_assistant_set_configuration
     */
    voice_assistant_set_configuration: {
      I: VoiceAssistantSetConfiguration,
      kind: MethodKind.Unary,
      name: 'voice_assistant_set_configuration',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.zwave_proxy_frame
     */
    zwave_proxy_frame: {
      I: ZWaveProxyFrame,
      kind: MethodKind.Unary,
      name: 'zwave_proxy_frame',
      O: void$,
    },
    /**
     * @generated from rpc APIConnection.zwave_proxy_request
     */
    zwave_proxy_request: {
      I: ZWaveProxyRequest,
      kind: MethodKind.Unary,
      name: 'zwave_proxy_request',
      O: void$,
    },
  },
  typeName: 'APIConnection',
} as const;
