version: v2
plugins:
  - local: protoc-gen-es
    out: .
    opt:
      - target=ts
      - import_extension=none
  - local: protoc-gen-connect-es
    out: .
    opt:
      - target=ts
      - import_extension=none