services:
  questdb:
    image: questdb/questdb:latest
    container_name: cove-questdb
    ports:
      - "9000:9000"  # HTTP API and web console
      - "9009:9009"  # InfluxDB line protocol
      - "8812:8812"  # PostgreSQL wire protocol (optional)
      - "9003:9003"  # Min health check
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - cove-network

networks:
  cove-network:
    name: cove-network