# yaml-language-server: $schema=./schemas/cove.schema.json

# Cove Home Automation System Configuration

# API Configuration
system:
  name: "Cove Home Automation"
  host: "0.0.0.0"  # Listen on all interfaces
  port: 4000
  service_advertisement:
    enabled: true
    service_type: "_cove._tcp.local."
    txt_records:
      type: "home_automation"
      version: "1.0"

# Device Discovery Configuration
discovery:
  protocols:
    - wifi:
        enabled: true
        discovery_timeout: 10
        discovery_interval: 10
        discovery_retries: 3
        discovery_retry_delay: 1
    - bluetooth:
        enabled: true
        discovery_timeout: 5
        discovery_interval: 30
        discovery_retries: 2
        discovery_retry_delay: 1
    - zigbee:
        enabled: false
        discovery_timeout: 5
        discovery_interval: 30
        discovery_retries: 2
        discovery_retry_delay: 1
    - matter:
        enabled: false
        discovery_timeout: 5
        discovery_interval: 30
        discovery_retries: 2
        discovery_retry_delay: 1

# Logging Configuration
logging:
  level: INFO
  file: "logs/cove.log"

# Device Persistence
storage:
  type: "file"
  path: "data/devices.json"
